-- =============================================================================
-- Migration 028 — CENTRE_DES_COUTS + lien postes
-- =============================================================================

BEGIN;

CREATE TABLE IF NOT EXISTS public.centre_des_couts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  denommination text,
  autre_info text,
  text text
);

COMMENT ON TABLE public.centre_des_couts IS 'Centres de coûts — référentiel pour les fiches de poste';
COMMENT ON COLUMN public.centre_des_couts.denommination IS 'Libellé du centre de coûts';
COMMENT ON COLUMN public.centre_des_couts.autre_info IS 'Informations complémentaires';
COMMENT ON COLUMN public.centre_des_couts.text IS 'Notes / texte libre';

ALTER TABLE public.postes
  ADD COLUMN IF NOT EXISTS centre_des_couts integer;

COMMENT ON COLUMN public.postes.centre_des_couts IS 'Référence logique → centre_des_couts.id';

CREATE INDEX IF NOT EXISTS idx_postes_centre_des_couts
  ON public.postes (centre_des_couts)
  WHERE centre_des_couts IS NOT NULL;

GRANT ALL ON TABLE public.centre_des_couts TO anon, authenticated, service_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role;

COMMIT;
