-- =============================================================================
-- Migration 030 — Hôpitaux affiliés (module Santé)
-- =============================================================================

BEGIN;

CREATE TABLE IF NOT EXISTS public."Hopitales" (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  hopital text NOT NULL,
  date_debut_contrat date,
  statut text,
  cout_total numeric(12, 2)
);

COMMENT ON TABLE public."Hopitales" IS 'Hôpitaux affiliés — contrats santé entreprise';

GRANT ALL ON TABLE public."Hopitales" TO anon, authenticated, service_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role;

COMMIT;
