-- =============================================================================
-- Migration 031 — Charroi automobile (véhicules, types de course, courses)
-- =============================================================================

BEGIN;

CREATE TABLE IF NOT EXISTS public.charroi_vehicules (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  immatriculation text NOT NULL,
  marque text,
  modele text,
  statut text NOT NULL DEFAULT 'disponible',
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.charroi_types_course (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  libelle text NOT NULL,
  description text
);

CREATE TABLE IF NOT EXISTS public.charroi_courses (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type_course_id bigint REFERENCES public.charroi_types_course (id) ON DELETE SET NULL,
  vehicule_id bigint REFERENCES public.charroi_vehicules (id) ON DELETE SET NULL,
  demandeur text NOT NULL,
  destination text,
  motif text,
  statut text NOT NULL DEFAULT 'demande',
  chauffeur_nom text,
  chauffeur_employe_id text,
  date_demande timestamptz NOT NULL DEFAULT now(),
  date_debut timestamptz,
  date_fin timestamptz
);

CREATE INDEX IF NOT EXISTS idx_charroi_courses_statut ON public.charroi_courses (statut);
CREATE INDEX IF NOT EXISTS idx_charroi_vehicules_statut ON public.charroi_vehicules (statut);

GRANT ALL ON TABLE public.charroi_vehicules TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.charroi_types_course TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.charroi_courses TO anon, authenticated, service_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role;

COMMIT;
