-- =============================================================================
-- Migration 032 — Visites hôpital (formulaire santé + file d'attente)
-- =============================================================================

BEGIN;

CREATE TABLE IF NOT EXISTS public.hopital_visite (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  matricule_agent text,
  hopital text,
  date_visite date,
  motif text,
  montant numeric(12, 2),
  fichiers jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by uuid,
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by uuid
);

COMMENT ON TABLE public.hopital_visite IS 'Visites médicales — formulaire et file d''attente santé';

GRANT ALL ON TABLE public.hopital_visite TO anon, authenticated, service_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role;

COMMIT;
