-- =============================================================================
-- Migration 035 — Parc véhicules (table vehicules)
-- =============================================================================

BEGIN;

CREATE TABLE IF NOT EXISTS public.vehicules (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  marque text NOT NULL,
  vehicle_type text,
  numero_chassis text UNIQUE,
  plaque text UNIQUE,
  province text,
  mise_circulation date,
  cv integer,
  centre_de_cout text,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by uuid,
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by uuid
);

COMMENT ON TABLE public.vehicules IS 'Parc automobile — charroi';

CREATE INDEX IF NOT EXISTS idx_vehicules_marque ON public.vehicules (marque);
CREATE INDEX IF NOT EXISTS idx_vehicules_province ON public.vehicules (province);
CREATE INDEX IF NOT EXISTS idx_vehicules_vehicle_type ON public.vehicules (vehicle_type);
CREATE INDEX IF NOT EXISTS idx_vehicules_centre_de_cout ON public.vehicules (centre_de_cout);

-- Réorienter les courses vers la nouvelle table (les anciennes références sont invalidées)
ALTER TABLE public.charroi_courses
  DROP CONSTRAINT IF EXISTS charroi_courses_vehicule_id_fkey;

UPDATE public.charroi_courses SET vehicule_id = NULL WHERE vehicule_id IS NOT NULL;

ALTER TABLE public.charroi_courses
  ADD CONSTRAINT charroi_courses_vehicule_id_fkey
  FOREIGN KEY (vehicule_id) REFERENCES public.vehicules (id) ON DELETE SET NULL;

GRANT ALL ON TABLE public.vehicules TO anon, authenticated, service_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role;

COMMIT;
