-- =============================================================================
-- Migration 036 — Types de course (table type_cours)
-- =============================================================================

BEGIN;

CREATE TABLE IF NOT EXISTS public.type_cours (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  designation text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by uuid,
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by uuid
);

COMMENT ON TABLE public.type_cours IS 'Référentiel des types de course — charroi';

CREATE INDEX IF NOT EXISTS idx_type_cours_designation ON public.type_cours (designation);

ALTER TABLE public.charroi_courses
  DROP CONSTRAINT IF EXISTS charroi_courses_type_course_id_fkey;

UPDATE public.charroi_courses SET type_course_id = NULL WHERE type_course_id IS NOT NULL;

ALTER TABLE public.charroi_courses
  ADD CONSTRAINT charroi_courses_type_course_id_fkey
  FOREIGN KEY (type_course_id) REFERENCES public.type_cours (id) ON DELETE SET NULL;

GRANT ALL ON TABLE public.type_cours TO anon, authenticated, service_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role;

COMMIT;
