-- =============================================================================
-- Migration 037 — Courses véhicule (demande, affectation, exécution)
-- =============================================================================

BEGIN;

CREATE TABLE IF NOT EXISTS public.courses_vehicule (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date_demande date NOT NULL,
  matricule_agent text NOT NULL,
  type_course_id bigint REFERENCES public.type_cours (id) ON DELETE SET NULL,
  depart text,
  destination text,
  motif text,
  vehicule_id bigint REFERENCES public.vehicules (id) ON DELETE SET NULL,
  chauffeur text,
  kmh_depart integer CHECK (kmh_depart IS NULL OR kmh_depart >= 0),
  kmh_arrive integer CHECK (kmh_arrive IS NULL OR kmh_arrive >= 0),
  niveau_carburant numeric(5, 2),
  passagers integer DEFAULT 0 CHECK (passagers >= 0),
  observations text,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by uuid,
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by uuid
);

-- Colonne statut (workflow demande → affecte → terminee)
ALTER TABLE public.courses_vehicule
  ADD COLUMN IF NOT EXISTS statut text;

UPDATE public.courses_vehicule
SET statut = CASE
  WHEN kmh_arrive IS NOT NULL OR kmh_depart IS NOT NULL THEN 'terminee'
  WHEN vehicule_id IS NOT NULL OR chauffeur IS NOT NULL THEN 'affecte'
  ELSE 'demande'
END
WHERE statut IS NULL;

ALTER TABLE public.courses_vehicule
  ALTER COLUMN statut SET DEFAULT 'demande';

UPDATE public.courses_vehicule SET statut = 'demande' WHERE statut IS NULL;

ALTER TABLE public.courses_vehicule
  ALTER COLUMN statut SET NOT NULL;

ALTER TABLE public.courses_vehicule
  DROP CONSTRAINT IF EXISTS courses_vehicule_statut_check;

ALTER TABLE public.courses_vehicule
  ADD CONSTRAINT courses_vehicule_statut_check CHECK (
    statut IN ('demande', 'affecte', 'terminee')
  );

COMMENT ON TABLE public.courses_vehicule IS 'Demandes et exécution de courses charroi';

CREATE INDEX IF NOT EXISTS idx_courses_vehicule_statut ON public.courses_vehicule (statut);
CREATE INDEX IF NOT EXISTS idx_courses_vehicule_date ON public.courses_vehicule (date_demande DESC);
CREATE INDEX IF NOT EXISTS idx_courses_vehicule_matricule ON public.courses_vehicule (matricule_agent);
CREATE INDEX IF NOT EXISTS idx_courses_vehicule_vehicule ON public.courses_vehicule (vehicule_id);

GRANT ALL ON TABLE public.courses_vehicule TO anon, authenticated, service_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role;

COMMIT;
